baseurl = "http://feature-cpp.github.io/feature.cpp/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "feature.cpp #nakamecpp"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = "東京・中目黒にて勉強会を開催中"
    github_repository = "https://github.com/feature-cpp/feature.cpp"
    version = "2"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/feature-cpp/"

    # Analytic section
    google_analytics_id = "UA-137874799-1" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archives", "blog", "entry", "post", "posts"]


# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/search?f=tweets&q=nakamecpp"
    weight = 2
